### ISSUE TITLE
Appreciate the hard work

### ISSUE THREAD

**Issue by prahjister** [treyfortmuller/greg#1]
Can you provide some basic instructions to use this? Sorry complete novice

**Comment by treyfortmuller** [comment]
Hey! No sweat at all, we're in the process of migrating this project here: https://github.com/Tessellate3D. We're calling it Tessellate. The readme there will have complete instructions and some quick start demos, etc. Give us about 2 or 3 weeks and we'll be thoroughly documented in the new repo.

**Comment by prahjister** [comment]
Ok great. I am starting a series on different structured light 3d scanner projects on www.cnx-software.com. I will keep an eye out. I would like to make people aware that they can do this themselves.

**Comment by treyfortmuller** [comment]
Got it. Definitely very possible to start from scratch. With some basic motion control and an Intel SR300 we're looking to get some professional quality results. More to come soon.
